# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# Snapback image configuration
image:
  repository: zarf.internal/snapback-operator
  tag: latest
  pullPolicy: IfNotPresent
