# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

FROM alpine:3.19

CMD ["sh", "-c", "while true; do date '+%Y-%m-%d %H:%M:%S'; sleep 10; done"]
