# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial
{{- include "snapback.validateRole" . -}}
{{- if eq .Values.role "source" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "snapback.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snapback.labels" . | nindent 4 }}
{{- end }}
