# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: v2
name: uds-snapback-config
description: UDS configuration chart for Snapback (Package CR — network policy + monitoring)
type: application
version: 0.1.0
appVersion: "0.1.0"
